spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
server:
  port: 19092

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/