spring:
  application:
    name: order-service
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

server:
  port: 19092

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/